@extends('accounts.insert')
@section('title', "Update Account - $x->username")
@section('box-title', "Update Account")
@section('form-action', "/accounts/update/".$x->id)
@section("usernameval", $x->username)
@section("join_dateval", $x->join_date)
@section("highscoreval", $x->highscore)
@section("countryval", $x->country_id)
@section("awardval", $x->awards)
